services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
       - LANG=en
       - WG_HOST={{ public_ip }}
       - PASSWORD_HASH={{ password_hash }}
       - PORT=51821
       - WG_PORT=51820
       - WG_ALLOWED_IPS=192.168.1.0/24
       - WG_DEFAULT_DNS=192.168.1.1
       - UI_CHART_TYPE=2
       - ENABLE_PROMETHEUS_METRICS=true
    volumes:
        - ~/.wg-easy:/etc/wireguard
    ports:
        - 51820:51820/udp
        - 80:51821/tcp
        - 443:51821/tcp
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv4.ip_forward=1
    restart: unless-stopped
