- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Change folder rights
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download docker gpg key 
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc 
    mode: '0644'

- name: Get dpkg architecture
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: False

- name: Get version codename
  shell: ". /etc/os-release && echo $VERSION_CODENAME"
  args:
    executable: /bin/bash
  register: version_codename
  changed_when: False

- name: Add docker repository
  copy: 
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ version_codename.stdout }} stable"

- name: Download docker
  apt:
    state: present
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Create wireguard folder
  file:
    path: ~/wireguard
    state: directory

- name: Copy docker compose file
  template:
    src: docker-compose.yaml
    dest: ~/wireguard/docker-compose.yaml

- name: Run docker compose
  community.docker.docker_compose_v2:
    project_src: ~/wireguard 
    state: present
